# Generated by Django 4.2.20 on 2025-03-30 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='', help_text='Тема на анкетата', max_length=100, verbose_name='Тема')),
                ('description', models.TextField(blank=True, default='', help_text='Описание на анкетата', verbose_name='Описание')),
                ('picture', models.ImageField(blank=True, upload_to='poll_pics', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Анкета',
                'verbose_name_plural': 'Анкети',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', help_text='Текст на въпроса', verbose_name='Текст')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'само с един отговор'), (2, 'с множествен избор на отговори')], default=1, help_text='тип на въпроса')),
                ('stat_attempts', models.IntegerField(default=0, help_text='генерира се автоматично', verbose_name='Брой отговори')),
                ('pool_id', models.ManyToManyField(blank=True, to='main.poll', verbose_name='id на анкета, в която се ползва')),
            ],
            options={
                'verbose_name': 'Въпрос',
                'verbose_name_plural': 'Въпроси',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='', help_text='Формулировка (текст) на опцията(отговора)', max_length=200, verbose_name='Текст')),
                ('checked', models.BooleanField(help_text='генерира се автоматично', null=True, verbose_name='Отговор')),
                ('stat_attempts', models.IntegerField(default=0, help_text='генерира се автоматично', verbose_name='Брой отговори')),
                ('question_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='main.question')),
            ],
            options={
                'verbose_name': 'Отговор на въпрос',
                'verbose_name_plural': 'Отговори на въпроси',
            },
        ),
    ]
