# Generated by Django 4.2.20 on 2025-03-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='active',
            field=models.BooleanField(default=True, help_text='Дали анкетата е видима за потребителите', verbose_name='Активна'),
        ),
    ]
